### ISSUE TITLE
Request Entity Too Large in 'create_stemcell'

### ISSUE THREAD

**Issue by deepakdefender264** [cloudfoundry-incubator/cf-openstack-validator#14]
Hi, I am trying to run cf-openstack-validator on one of the ubuntu to validate our openstack cloud but getting below error.
Can anyone help on this.
Your OpenStack using the CPI can save a stemcell
     Stemcell could not be uploaded OpenStack error: CPI error 'Unknown' with message 'Expected(204) <=> Actual(413 Request Entity Too Large)
excon.error.response
  :body          => "<html>\r\n<head><title>413 Request Entity Too Large</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>413 Request Entity Too Large</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
  :cookies       => [
  ]
  :headers       => {
    "Connection"     => "close"
    "Content-Length" => "192"
    "Content-Type"   => "text/html"
    "Date"           => "Thu, 27 Apr 2017 08:53:28 GMT"
    "Server"         => "nginx"
  }
  :host          => "xxxxxxx"
  :local_address => "192.168.1.152"
  :local_port    => 59246
  :path          => "/v2/images/667993e2-5a80-45fc-8efb-6b3a01564a5f/file"
  :port          => 443
  :reason_phrase => "Request Entity Too Large"
  :remote_ip     => "100.125.1.20"
  :status        => 413
  :status_line   => "HTTP/1.1 413 Request Entity Too Large\r\n"
' in 'create_stemcell' CPI method

Finished in 4 minutes 47.7 seconds (files took 0.1601 seconds to load)
27 examples, 1 failure, 20 pending
Resources: All resources have been cleaned up

You can find more information in the logs at /home/atmf/.cf-openstack-validator/logs/testsuite.log

**Comment by voelzmo** [comment]
It seems like you do not have enough space to store the image. Is this a devstack or an installation of hardware?

**Comment by deepakdefender264** [comment]
I have sufficient space on he VM on which I am running this utility. But seems something is stopping to upload 555 mb stemcell. I am trying to run this utility on one of the inhouse openstack environment.

**Comment by deepakdefender264** [comment]
Hi Marco, you might be right. The vm creating from the below config had only 4gb of ram due to instance type and image I had chosen. After changing image. the default root disk increased to 12 gb.

Validator.yml ->
openstack:
  auth_url: https://xxxxxx:443/v3  # Keystone V3 URL
  username: "xxxxxxxxxxxxxxx" # String
  password: xxxxxxxxxxxxxx  # String
  domain: xxxxxxxxxxxxxxx # String
  project: xxxxxx # String
  default_key_name: cf-validator # String
  default_security_groups: [cf] # List of String
  boot_from_volume: false # Boolean
  config_drive: ~ # One of cdrom, disk, or nil
  connection_options: # all connection options that are supported by Excon
    connect_timeout: 3600
    ssl_verify_peer: false # Boolean
    # ca_cert: <replace-me> # Multiline yaml String containing certificate chain

validator:
  network_id: xxxxxxxxxxxxxx # String UUID
  floating_ip: xxxxxxxxxxxxx # String IP
  static_ip: 192.168.1.160 # String IP. This IP is used to create a VM with a static IP.
  private_key_path: cf-validator.rsa_id # relative to validator.yml, no absolute path supported
  public_image_id: xxxxxxxxxxxxxxxxxxx # String UUID
  ntp: [0.pool.ntp.org, 1.pool.ntp.org] # List of String
  releases:
  - name: bosh-openstack-cpi
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-openstack-cpi-release?v=30
    sha1: 2fff8e1c241a91267ddd099a553c1339d2709821

cloud_config:
  vm_types: # See https://bosh.io/docs/cloud-config.html#vm-types
  - name: default # Don't change this name
    cloud_properties:
      instance_type: s1.large # String
      availability_zone: xxxxxx # String
      root_disk:
       size: 50 # Integer, size in GiB. Used together with openstack.boot_from_volume.

extensions:
  paths: [] # paths pointing to a directory. Absolute or relative to this config file.
  config: {} # everything below 'config' is available in tests as `Validator::Api.configuration.extensions` inside your test code

**After running above yaml with ubuntu stemcell, I am having these issues -**
**Issue 1:**  On mentioning ['default'].cloud_properties.root_disk to 50, new vm is still creating with 12 gb of disk.

**Issue 2:** After using another public image now I am getting below error
Failures:
  1) Your OpenStack using the CPI can save a stemcell
     Stemcell could not be uploaded OpenStack error: CPI error 'Unknown' with message 'can't convert NilClass into time interval' in 'create_stemcell' CPI method

**Comment by voelzmo** [comment]
please format your configuration correctly, so we can see the indentation. yaml is very picky about this.

I can see that you have set `boot_from_volume: false`. In order to configure the disk size independent of your flavor's disk definitions, you need to set this to `true`. I've [documented this](https://github.com/cloudfoundry-incubator/cf-openstack-validator/blob/master/docs/openstack_configurations.md#using-custom-ephemeral-disk-size) more clearly now. 

You cannot use arbitrary public images as stemcells. BOSH stemcells contain the BOSH agent, pre-configured settings and come with specific metadata about the image. You need to pass in an actual OpenStack BOSH stemcell into the validator with `--stemcell` on the commandline.

Out of curiosity: Why are you trying to change disk sizes and stemcells?

**Comment by loewenstein** [comment]
Hi @deepakdefender264,

Is this still current? If you still see the problems, please format your config as code block, so that it keeps corrent indentation.

Best
Jan

**Comment by voelzmo** [comment]
Closing for now, feel free to re-open with more information if necessary.
