### ISSUE TITLE
MTU test fails 

### ISSUE THREAD

**Issue by axel7born** [cloudfoundry-incubator/cf-openstack-validator#15]
Hi,
I get the following failure running the validator:

```
Failures:

  1) Your OpenStack using the CPI has configured MTU size
     Failure/Error: actual_mtu_size = output.match(/=(\d+)/)[1]
     
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./src/specs/cpi_lifecycle_spec.rb:367:in `block (2 levels) in <top (required)>'
     # ./lib/validator/cli/cf_openstack_validator.rb:193:in `block in execute_specs'
     # ./lib/validator/cli/cf_openstack_validator.rb:192:in `open'
     # ./lib/validator/cli/cf_openstack_validator.rb:192:in `execute_specs'
     # ./lib/validator/cli/cf_openstack_validator.rb:22:in `run'

```

The pattern match fails, as there is no mtu in the output. Running traceroute manually results in the following output:
```
/:~$ sudo -S traceroute -M raw  -m 1 --mtu 10.0.1.220
traceroute to 10.0.1.220 (10.0.1.220), 1 hops max, 65000 byte packets
 1  host-10-0-1-220.openstack.local (10.0.1.220)  1.427 ms !P  0.239 ms !P  0.155 ms !P
```
It seems that traceroute doesn't show the mtu size for method raw. For default mode or explicit udp, I can see the mtu size in the output:

```
/:~$ sudo -S traceroute   -m 1 --mtu 10.0.1.220
traceroute to 10.0.1.220 (10.0.1.220), 1 hops max, 65000 byte packets
 1  host-10-0-1-220.openstack.local (10.0.1.220)  1.467 ms F=1500  0.270 ms  0.231 ms
/:~$ sudo -S traceroute -M udp  -m 1 --mtu 10.0.1.220
traceroute to 10.0.1.220 (10.0.1.220), 1 hops max, 65000 byte packets
 1  host-10-0-1-220.openstack.local (10.0.1.220)  1.129 ms F=1500  0.243 ms  0.310 ms
```

I tested with stemcell bosh-stemcell-3363.24-openstack-kvm-ubuntu-trusty-go_agent.tgz

**Comment by BRuhland** [comment]
Failures:

  1) Your OpenStack using the CPI has configured MTU size
     undefined method `[]' for nil:NilClas

**Comment by axel7born** [comment]
I made some tests with traceroute in an openstack tenant. It seems that traceroute outputs a result for mtu, if the two instances are not on the same network. If the instances are on the same network, the outputs indicates !P - Protocol unreachable.
```
/:~$ sudo traceroute -M raw -m 1 --mtu 10.0.1.209
traceroute to 10.0.1.209 (10.0.1.209), 1 hops max, 65000 byte packets
 1  host-10-0-1-209.openstack.local (10.0.1.209)  1.403 ms !P  0.303 ms !P  0.165 ms !P
/:~$ sudo traceroute -M raw -m 1 --mtu 10.3.0.5
traceroute to 10.3.0.5 (10.3.0.5), 1 hops max, 65000 byte packets
 1  10.0.1.1 (10.0.1.1)  0.267 ms F=1500  1.161 ms  0.139 ms
```

**Comment by Kiemes** [comment]
Maybe the OpenStack setup does not allow the 'raw' protocol. According to the man page `traceroute` uses protocol 253 by default. This can be changed by using `-P n`.

However we should parse the error flags mentioned in the documentation: 
```
After the trip time, some additional annotation can be printed: !H, !N, or !P (host, network or  protocol  unreachable)
```

**Comment by loewenstein** [comment]
Raw is working quite well in CI. 

I would like to stick with `raw` unless we have very good reasons not to. It does not require special security group rules as the other methods would most probably need.

**Comment by mauromorales** [comment]
@voelzmo The original issue with the `undefined method `[]' for nil:NilClass` has been fixed. However, we did encountered this issue:

```
Your OpenStack
  using the CPI
    against OpenStack
      can save a stemcell... passed
      can attach floating IP to a VM... passed
      allows a VM to reach the configured NTP server... passed
      can create a VM with static IP... passed
      has configured MTU size... failed

Failures:

  1) Your OpenStack using the CPI against OpenStack has configured MTU size

     MTU size could not be checked.
     Executed remote command: $ echo 'c1oudc0w' | sudo --prompt "" --stdin traceroute -M raw -m 1 --mtu 10.10.0.20
     stderr: 
             
     stdout: traceroute to 10.10.0.20 (10.10.0.20), 1 hops max, 65000 byte packets
              1  host-10-10-0-20.openstack.local (10.10.0.20)  1782.212 ms !P  0.535 ms !P  0.533 ms !P

```

The good thing is that the error states that the problem was MTU couldn't be checked but if we know why it couldn't be checked maybe we could either make the test more robust and add/remove the `-M raw` when necessary or at least point the user to what is the required configuration to run this test.
