### ISSUE TITLE
NTP test fails with latest stemcell

### ISSUE THREAD

**Issue by mauromorales** [cloudfoundry-incubator/cf-openstack-validator#26]
NTP test fails when run using stemcell: `bosh-stemcell-3541.5-openstack-kvm-ubuntu-trusty-go_agent.tgz`  with the following error:

```
  1) Your OpenStack using the CPI against OpenStack allows a VM to reach the configured NTP server
     Failed to reach any of the following NTP servers: 0.pool.ntp.org, 1.pool.ntp.org. If your OpenStack requires an internal time server, you need to configure it in the validator.yml.
     Executed remote command: $ echo 'c1oudc0w' | sudo --prompt "" --stdin /var/vcap/bosh/bin/ntpdate
     stderr: 
             sudo: /var/vcap/bosh/bin/ntpdate: command not found
             
     stdout: 


```

Our pipelines are currently using: `bosh-stemcell-3541.5-openstack-kvm-ubuntu-trusty-go_agent.tgz` so I guess this issue might affect a bunch of other stemcells in between these two.

**Comment by voelzmo** [comment]
This might have been changed with the 3541.x series, not sure when this change was introduced.

**Comment by markstokan** [comment]
We ran into this today and found a reference to the change in the bosh stemcell release notes [here](https://docs.pivotal.io/pivotalcf/2-3/stemcells/stemcells.html#3541-line)

```
3541.2
Release Date: February 08, 2018
[breaking] Renamed /var/vcap/bosh/bin/ntpdate to /var/vcap/bosh/bin/sync-time
```

**Comment by voelzmo** [comment]
Thanks for digging this up, @markstokan!
We will prioritize this story soon and have it fixed for the newer stemcells.

**Comment by friegger** [comment]
This has been fixed with https://github.com/cloudfoundry-incubator/cf-openstack-validator/commit/39cfd24a3ee0774719b7cce5614635ce6d3ddfe2.
