### ISSUE TITLE
cleanup script doesn't fail when it should

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry-incubator/cf-openstack-validator#32]
`set -e` isn't enough when you're using pipes and such: https://github.com/cloudfoundry-incubator/cf-openstack-validator/blob/master/ci/tasks/cleanup.sh#L3. We should use the more safe `set -euxo pipefail`, see https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/

Context: [selecting the project name](https://github.com/cloudfoundry-incubator/cf-openstack-validator/blob/master/ci/tasks/cleanup.sh#L9) should never be allowed to result in an empty project name, because using admin credentials this would also select ports from other projects.

**Comment by friegger** [comment]
This has been fixed in the meantime.
