### ISSUE TITLE
MTU size could not be checked with bosh stemcell 170.21

### ISSUE THREAD

**Issue by iBender70** [cloudfoundry-incubator/cf-openstack-validator#34]
When running the validation with the current bosh stemcell 170.21 I get an error for the MTU size check:

```
  1) Your OpenStack validating configuration connectivity has configured MTU size
     MTU size could not be checked.
     Executed remote command: $ echo 'c1oudc0w' | sudo --prompt "" --stdin traceroute -M raw -m 1 --mtu 192.168.0.100
     stderr:

     stdout: traceroute to 192.168.0.100 (192.168.0.100), 1 hops max, 65000 byte packets
              1  vm-e8a34d2e-0553-4249-935e-d3f77adfbe13.openstack.local (192.168.0.100)  1.577 ms !P  0.315 ms !P  0.225 ms !P
```

**Comment by s4heid** [comment]
Hi @iBender70,

sorry for the inconvenience and thanks for submitting this issue. We finally decided to remove the MTU test from our validator test suite (https://github.com/cloudfoundry-incubator/cf-openstack-validator/commit/96e038972c1bd5c77e9ad5694682ea601e125630). There are many edge cases, and covering them all is almost impossible. As a result, the reliability of this test was very limited.

In case there are other opinions, we are open for discussions.

Best Regards,
s4heid && @langered, CF BOSH Europe
